const CONFIG = {
    introTitle: 'Ê Hà ơi !',
    introDesc: `Ấn vào t bảo`,
    btnIntro: 'hihi',
    title: 'Đi đạp xe lên HN k nào ^^',
    desc: ' Chỉ hơn 50km thôi :vvv !',
    btnYes: 'Có chứ, háo hức lắm',
    btnNo: 'Khồng, gãy chân đấy :3',
    question:'Trên thế giới hơn 7 tỉ người mà sao cậu lại đạp xe với tớ?',
    btnReply: 'Send',
    reply: 'Mình thích thì mình đạp thôi',
    mess: 'Tớ biết mà, mai 6h gặp nhau trc cửa nhé :vvvv',
    messDesc: 'Đừng cho tớ leo cây đấy',
    btnAccept: 'Okiiiii lun',
}
